#!/usr/bin/env python
# -*- coding: us-ascii -*-
# generated by wxGlade 0.6.3 on Sun Jul 13 20:19:10 2008

import wx
from PhromsFrame import PhromsFrame
from twisted.internet import wxreactor

if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    wxreactor.install()
    
    frame_1 = PhromsFrame(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    # Use the wx reactor instead
    app.MainLoop()
    #reactor.registerWxApp(app)
    #reactor.run()
