default: {ConnectionType: initiator, EndTime: '00:00:00', FileLogPath: log, FileStorePath: store,
	     HeartBtInt: '30', ReconnectInterval: '1', SocketConnectHost: localhost, StartTime: '00:00:00',
    	     UseDataDictionary: N, HttpAcceptPort: '9001'}
sessions:
# - {ConnnectionType: initiator, BeginString: FIX.4.2, SenderCompID: CSFB,    SocketConnectPort: '1666', TargetCompID: GSA, ConnectionType : initiator}
  - {ConnectionType:  acceptor , BeginString: FIX.4.2, SenderCompID: PHROMS_NATIVE, SocketConnectPort: '5003', TargetCompID: NATIVE_EXECUTOR}
  - {ConnectionType:  acceptor , BeginString: FIX.4.2, SenderCompID: GSA,    SocketAcceptPort: '1666', TargetCompID: CSFB   , DefaultAccount: ACCOUNT1}
  - {ConnectionType:  acceptor , BeginString: FIX.4.2, SenderCompID: PHROMS, SocketAcceptPort: '5011', TargetCompID: SENDER , DefaultAccount: ACCOUNT2 }



