default: {ConnectionType: initiator,
          HeartbeatInterval: 30, 
          PersistRoot: ../persist/send ,
          Host: localhost,
          ConnectionType : initiator}
sessions:
  - { BeginString: FIX.4.2, SenderCompID: ACME, Port: 1666, TargetCompID: BROKER }
manhole:
  listenPort: 2223
  passwords: { admin : aaa }
ftpServer:
  passwords: { admin : aaa }
webServer:
  listenPort: 8001
nevow:
  listenPort: 8002

  




